#!/usr/bin/env python3
"""Simulation 4: matched standard quantum state, different SoCT memory histories.

Two qubits start in the same |+> state with the same ordinary Hamiltonian and
current environment. The standard null model sets lambda_M=0 and predicts
identical evolution. The exploratory SoCT arm assigns different memory initial
conditions M_A(0), M_B(0) inherited from different prior record-production
histories and couples them through H_M = lambda_M M(t) sigma_z.

Units are dimensionless with hbar=1. This is a mechanism/discriminator toy
model, not evidence for physical memory feedback.
"""

import csv
import math
from pathlib import Path


def phase_integral(omega: float, lam: float, m0: float, beta: float, t: float) -> float:
    """Integral of a(t) for H(t)=a(t) sigma_z, a=omega/2+lam*M(t)."""
    ordinary = 0.5 * omega * t
    if beta == 0.0:
        memory = lam * m0 * t
    else:
        memory = lam * m0 * (1.0 - math.exp(-beta * t)) / beta
    return ordinary + memory


def p_plus(phase: float) -> float:
    """Return probability to |+> after z rotation generated by a sigma_z."""
    return math.cos(phase) ** 2


def main():
    out = Path(__file__).with_name("results.csv")

    omega = 1.0
    beta = 0.25
    m_a0 = 0.0
    m_b0 = 1.0
    lambdas = [0.0, 0.01, 0.03, 0.1]
    times = [0.0, 1.0, 2.0, 4.0, 8.0]

    rows = []
    for lam in lambdas:
        for t in times:
            phase_a = phase_integral(omega, lam, m_a0, beta, t)
            phase_b = phase_integral(omega, lam, m_b0, beta, t)
            pa = p_plus(phase_a)
            pb = p_plus(phase_b)
            rows.append({
                "lambda_M": lam,
                "time": t,
                "M_A0": m_a0,
                "M_B0": m_b0,
                "beta": beta,
                "phase_A": phase_a,
                "phase_B": phase_b,
                "delta_phase": phase_b - phase_a,
                "Pplus_A": pa,
                "Pplus_B": pb,
                "delta_Pplus": pb - pa,
            })

    with out.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)

    print(f"wrote {out}")


if __name__ == "__main__":
    main()
